### ISSUE TITLE
Tracking issue for user experience

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#398]
Menu:
- [x] add a repository
  - [x] specify branch(es)
  - [x] specify commit(s) for each branch
  - [x] specify tools
- [x] remove
  - [x] remove a repository
  - [x] remove a tool
- [x] build
  - [x] build all tools in a repository
  - [x] build a tool
- [x] list
  - [x] list repositories
  - [x] list tools of a repository
  - [x] list all tools
- [x] data
  - [x] add a file for processing
  - [x] listen on a nic
- [x] services
  - [x] get exposed service URIs
- [x] cores
  - [x] install cores
  - [x] build cores
  - [x] start cores
  - [x] stop cores
  - [x] clean cores
  - [x] update cores
  - [x] remove cores
- [x] editor
  - [x] change configuration files
  - [x] change templates
- [x] help
- [x] logs
- [x] reset
- [x] backup
- [x] restore
- [ ] upgrade
- [ ] cluster vent instances
