### ISSUE TITLE
Tracking issue for documentation

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#401]
- [x] README
- [x] document cores
- [x] document getting started
- [x] document expected user experience (i.e. sending data to get processed by plugins)
- [x] document expected developer experience (i.e. writing plugins)
- [x] document templates
- [x] code documentation

**Comment by Jeff-Wang93** [comment]
`document templates` 

This is talking about `vent.template` files of custom Vent plugins correct?

**Comment by cglewis** [comment]
correct.
